# Generated by Django 3.0.1 on 2020-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('address', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(verbose_name=10)),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('donate_catagory', models.CharField(max_length=50)),
                ('donate_amt', models.IntegerField()),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PoorDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('address', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(verbose_name=10)),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('donate_catagory', models.CharField(max_length=50)),
                ('donate_amt', models.IntegerField()),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
    ]
